name: flutter_betting_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  redux: ^5.0.0
  flutter_redux: ^0.8.2
  stomp_dart_client: ^0.4.4
  redux_thunk: ^0.4.0
  flutter_countdown_timer: ^4.1.0
  http: ^0.13.5
  intl: ^0.17.0
  jiffy: ^5.0.0
  easy_localization: ^3.0.1
  flutter_launcher_icons: ^0.10.0
  package_info_plus: ^1.4.3
  url_launcher: ^6.1.6
  flutter_keyboard_visibility: ^5.3.0
  share: ^2.0.4
  scrollable_positioned_list: ^0.3.5
  firebase_core: ^1.24.0
  firebase_messaging: ^13.1.0
  firebase_analytics: ^9.3.8
  webview_flutter: ^3.0.4
  intl_phone_number_input: ^0.7.0+2
  sliver_tools: ^0.2.8
  sliding_up_panel: ^2.0.0+1
  styled_text: ^5.1.0
  carousel_slider: ^4.1.1
  country_icons: ^2.0.2
  flutter_inappwebview: ^5.4.4+3
  device_apps: ^2.2.0
  android_intent_plus: ^3.1.2
  flutter_secure_storage: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
     - assets/images/koolbet/logo/
     - assets/images/koolbet/slides/en/
     - assets/images/koolbet/slides/fr/
     - assets/images/koolbet/jackpot/
     - assets/images/grandbet/logo/
     - assets/images/grandbet/jackpot/
     - assets/images/betpalace/logo/
     - assets/images/betpalace/slides/
     - assets/images/bonuses/xmas_bonus.png
     - assets/images/payment_logo/mpesa_logo.png
     - assets/images/payment_logo/mpesa-kenya-logo.png
     - assets/images/payment_logo/mtn-logo-small.png
     - assets/images/payment_logo/om_logo.png
     - assets/images/payment_logo/om_cam_logo.png
     - assets/images/payment_logo/hellocash.png
     - assets/images/payment_logo/telebirr_logo.png  
     - assets/images/payment_logo/cash_internal_deposit.png
     - assets/images/payment_logo/cash_internal_grandbet.png
     - assets/images/payment_logo/cash_internal_withdraw.png
     - assets/translations/
     - assets/images/top-tournament/
     - assets/countries/
     - assets/html/demo7/tvBet.html
     - assets/html/koolbet/tvBet.html
     - assets/html/betpalace/tvBet.html
    

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: AppIcons
    fonts:
    - asset: assets/fonts/AppIcons.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
